host: 0.0.0.0
# Site settings
title: "Aniket's Resume"
description: "A resume hosting via Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Aniket Gawade"
resume_title:                   "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "aniketjgawade@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "323-434-5545"
resume_contact_address:         "San Francisco Bay Area"

resume_header_contact_info:     "SF Bay Area • <a href=\"tel:323-434-5545\">323-434-5545 </a> • <a href=\"mailto:aniketjgawade@gmail.com\">aniketjgawade@gmail.com </a> • <a href=\"https://www.linkedin.com/in/aniketgawade\">LinkedIn</a>"
display_header_contact_info:    "true"

resume_header_intro: >
  <p><b>Summary</b> Senior Software Engineer with 14+ years of expertise in designing and deploying highly scalable backend systems, distributed architectures, and cloud-based solutions. Proven track record of leading teams, mentoring engineers, and delivering innovative projects, including patent-pending technologies. Skilled in ETL pipelines, LLM fine-tuning, and network infrastructure management, with hands-on experience in Golang, Python, Kubernetes, and AWS/GCP services. Adept at optimizing performance, driving automation, and exceeding benchmarks in diverse technical domains.</p>
  <p><b>Areas of Interests</b> Monitoring and Analytics, Distributed Systems, Generative AI, Cloud Systems, Networking, Infrastructure & Security.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/aniketgawade"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/aniketgawade"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
